name: Build, Test and Deploy on Develop BE 
on:
  push:
    branches:
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Install Maven dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn clean install
      
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'  
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Run Tests with Maven
      run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out código
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'  
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Docker image
        run: |
          mvn clean package -DskipTests
          docker build --build-arg JAR_FILE=target/payments-service-example-0.0.1-SNAPSHOT.jar -t payments-service-example:staging .
      
      - name: Log in to AWS ECR
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          
          AWS_LOGIN_COMMAND=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }})
          echo $AWS_LOGIN_COMMAND | docker login --username AWS --password-stdin ${{ secrets.AWS_REGION }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Tag and Push Docker image to AWS
        run: |
          docker tag payments-service-example:develop $AWS_REGION.dkr.ecr.$AWS_REGION.amazonaws.com/proyecto-devops-gg-service:develop
          docker push $AWS_REGION.dkr.ecr.$AWS_REGION.amazonaws.com/proyecto-devops-gg-service:develop

