name: CI/CD with Maven

on:
  push:
    branches:
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Maven dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn clean install
  
  
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Run Tests with Maven
      run: mvn test